# Generated by Django 5.1.3 on 2025-01-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_webpage_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecords',
            old_name='webpage',
            new_name='name',
        ),
    ]
