# Generated by Django 5.1.3 on 2025-01-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='brand',
        ),
    ]
