# Generated by Django 5.1.3 on 2025-01-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='Price',
        ),
    ]
